Update Auto-Sklearn Setup file
openml/automlbenchmark pull request #309
Opened 2021-05-19 18:23 UTC by franchuterivera

This PR enhances Auto-Sklearn setup with 2 changes:

1- In auto-sklearn's workflow, the master branch refers to the stable release. We want to make this clear via the setup.sh
2- We want to be able to provide both hash/branch names as a version, as this enables us to test (within the automlbenchmark umbrella) different auto-sklearn versions.

2021-05-19 18:56 UTC, sebhrusen requested changes
@franchuterivera your changes are completely removing the current support for branches and changing the semantics.

currently when specifying a framework version in a framework definition file the expectations are as follow for all frameworks:
- version: 0.12.6    will install this release if available.
- version: stable    will install the most recent stable version (from pip) if available: for frameworks that don't provide any release, we accept 'stable' pointing to a branch.
- version:  latest    will install the latest build (not officially release), can also point to a master or dev branch.
- version: my_branch   will install from the givne branch name.

With your changes, there's no possibility anymore to specify a branch.
If you want to use master, please just create a local definition for yourself with `version: latest`.

2021-05-19 19:00 UTC, sebhrusen commented on frameworks/autosklearn/setup.sh
> +    cd ${HERE}
we don't need to pull the entire repo just to run `autosklearn`, why removing the `--depth`, `--single-branch` and `--branch` arguments?

2021-05-19 19:04 UTC, sebhrusen commented
@franchuterivera 
> 1- In auto-sklearn's workflow, the master branch refers to the stable release. We want to make this clear via the setup.sh

if you mean that `master` contains the same code as the latest release available from pip, then the relevant change would be:
```
if [[ "$VERSION" == "latest" ]]; then
    VERSION="dev"  # or whatever your main dev branch is
fi
```
As soon as you have a release build, it's better to install the `stable` release from pip than from `master` branch in that case`.

> 2- We want to be able to provide both hash/branch names as a version, as this enables us to test (within the automlbenchmark umbrella) different auto-sklearn versions.

Is this the reason why you removed the `--depth` ... arguments?

2021-06-28 11:04 UTC, franchuterivera commented
Hello, sorry for the delay in the reply. I have incorporated your feedback. Please let me know if you think this can be further improved, but I have checked with @mfeurer and from our side, this looks ok.

2021-06-28 11:05 UTC, franchuterivera commented
BTW, I tried changing the 'version' field in the `resources/framework.yml` yet it kept selecting stable for me.

Is there a way one can easy change the version from the command line? I was trying to search the documentation but I could not find a nice way (and ended up hardcoding the version for testing.)

2021-07-20 13:32 UTC, PGijsbers commented
I updated the PR so it saves the hash to `.installed` (if a branch is specified, the hash is first retrieved so the version is still unique). In the process I converted it to a similar workflow as the R setup mentioned. In the future we can probably use some shared functions instead. 

There is currently an issue creating docker containers (the `#` in the version creates an invalid tag). I suppose that could also be dealt with in a separate PR (since it's already present with the R frameworks, I just hadn't noticed because I had to test those on aws).

2021-07-20 13:36 UTC, PGijsbers commented
I did undo some of the optimization, I'll patch that back in.

2021-07-20 15:02 UTC, sebhrusen commented on frameworks/autosklearn/setup.sh
> +      COMMIT=$(git ls-remote "${REPO}" | grep "refs/heads/${VERSION}" | cut -f 1)
why to we need the commit when we specify a branch?
Then it forces us to clone the entire repository when we used to need to clone only the specific branch without history... it's a bit silly to clone a full repo when you're not planning to work on it.

2021-07-20 15:04 UTC, sebhrusen commented on frameworks/autosklearn/setup.sh
> +      COMMIT=$(git ls-remote "${REPO}" | grep "refs/heads/${VERSION}" | cut -f 1)
ok, I guess this optimization was temporarily removed.

2021-07-20 15:18 UTC, PGijsbers commented on amlb/runners/container.py
> +        tag = re.sub(r"^\.+", "", tag)
Absolutely right 👍

2021-07-21 12:13 UTC, PGijsbers commented
Verified on AWS and Docker for both branch and specific commit.

2021-07-21 14:30 UTC, sebhrusen approved these changes
Looks good to me, thanks @franchuterivera and @PGijsbers

2021-07-21 14:30 UTC, sebhrusen commented on frameworks/autosklearn/setup.sh
> +  truncate -s-1 "${HERE}/.installed"
do you need this to remove the last NL?

2021-07-22 09:21 UTC, PGijsbers commented on frameworks/autosklearn/setup.sh
> +  truncate -s-1 "${HERE}/.installed"
Exactly the purpose :)

2021-07-22 09:23 UTC, merged