MLNet - Add option for picking up trainers
openml/automlbenchmark pull request #327
Opened 2021-06-18 19:37 UTC by LittleLittleCloud

default trainers are
- lgbm
- rf
- fast tree
- sdca
- lbfgs

2021-06-21 14:24 UTC, sebhrusen requested changes

2021-06-21 14:24 UTC, sebhrusen commented on resources/frameworks.yaml
> +
non-default params are not allowed in this file, if you need to try different configurations for your personal use, please add your own definitions in `~/.config/automlbenchmark/framework.yaml`
See https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#custom-configuration for details

2021-06-21 14:24 UTC, sebhrusen commented on frameworks/MLNet/exec.py
> +    os.environ['AutoMLServiceRegressors'] = allowedRegressors
As these are not purely technical parameters but a way to configure the behaviour of MLNET, we can't allow passing non-default values here.
Also, by convention, parameters that are not passed directly to the training function (in your case, to `run_cmd(cmd)` below) must be prefixed with underscore.

Summing up these 2 concerns, we can only accept something like:
```suggestion
    allowedMultiClassifiers = config.framework_params.get('_classifiers')
    allowedRegressors = config.framework_params.get('regressors')
    if allowedMultiClassifiers is not None:
        os.environ['AutoMLServiceMultiClassifiers'] = allowedMultiClassifiers
    if allowedRegressors is not None:
        os.environ['AutoMLServiceRegressors'] = allowedRegressors
```

2021-09-06 08:19 UTC, PGijsbers commented
If @LittleLittleCloud does not respond soon I will close this PR. It can always be re-opened if needed.

2021-09-08 18:58 UTC, LittleLittleCloud commented
This PR is also based on pretty old commit, you can close it for now.

2021-09-09 08:05 UTC, closed without merging